# Generated by Django 5.0 on 2023-12-30 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-dateandtime']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateandtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
