# Generated by Django 5.0 on 2023-12-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
